FROM alpine:3.17.1

ARG TARGETARCH

RUN apk add --no-cache python3 py3-pip curl ca-certificates openssh-server rsync \
	&& apk add --no-cache --virtual .build-deps git \
	&& curl -L -O https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-${TARGETARCH}.tgz \
	&& tar -xzf ngrok-v3-stable-linux-${TARGETARCH}.tgz \
	&& install -v -D ngrok /usr/local/bin/ngrok \
	&& pip install supervisor
RUN pip install git+https://github.com/suda/supervisord-dependent-startup.git \
	&& curl -L -o jq https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-${TARGETARCH} \
	&& install -v -D jq /usr/local/bin/jq \
	&& rm -f ngrok-v3-stable-linux-${TARGETARCH}.tgz ngrok jq \
	&& apk del .build-deps

# RUN
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

COPY etc/ /etc
COPY bin/ /usr/local/bin/

ENTRYPOINT ["supervisord", "--nodaemon", "--configuration", "/etc/supervisord.conf"]
